=== concretecms/concretecms/tests/assets/Block/cif/options-schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "requiredBlockTypes": {
        "type": "array",
        "items": {
            "type": "string",
            "minLength": 1
        },
        "uniqueItems": true
    },
    "importerExporterMethod": {
        "type": "string",
        "minLength": 1
    },
    "fileUsageCount": {
      "type": "integer",
      "minimum": 0
    },
    "richTextsWithPages": {
      "type": "object",
      "additionalProperties": {
        "type": "integer",
        "minimum": 0
      }
    },
    "richTextsWithImages": {
      "type": "object",
      "additionalProperties": {
        "type": "integer",
        "minimum": 0
      }
    },
    "richTextsWithFiles": {
      "type": "object",
      "additionalProperties": {
        "type": "integer",
        "minimum": 0
      }
    }
  },
  "required": [
  ],
  "additionalProperties": false
}

=== concretecms/concretecms/tests/assets/Block/cif/faq/1.json
{
    "$schema": "../options-schema.json",
    "fileUsageCount": 2,
    "richTextsWithPages": {
        "SELECT description FROM btFaqEntries WHERE bID = :bID ORDER BY sortOrder LIMIT 0,1": 1,
        "SELECT description FROM btFaqEntries WHERE bID = :bID ORDER BY sortOrder LIMIT 1,1": 0,
        "SELECT description FROM btFaqEntries WHERE bID = :bID ORDER BY sortOrder LIMIT 2,1": 1
    },
    "richTextsWithFiles": {
        "SELECT description FROM btFaqEntries WHERE bID = :bID ORDER BY sortOrder LIMIT 0,1": 0,
        "SELECT description FROM btFaqEntries WHERE bID = :bID ORDER BY sortOrder LIMIT 1,1": 1,
        "SELECT description FROM btFaqEntries WHERE bID = :bID ORDER BY sortOrder LIMIT 2,1": 0
    },
    "richTextsWithImages": {
        "SELECT description FROM btFaqEntries WHERE bID = :bID ORDER BY sortOrder LIMIT 0,1": 0,
        "SELECT description FROM btFaqEntries WHERE bID = :bID ORDER BY sortOrder LIMIT 1,1": 0,
        "SELECT description FROM btFaqEntries WHERE bID = :bID ORDER BY sortOrder LIMIT 2,1": 1
    }
}

=== concretecms/concretecms/tests/assets/Block/cif/accordion/1.json
{
    "$schema": "../options-schema.json",
    "fileUsageCount": 2,
    "richTextsWithPages": {
        "SELECT description FROM btAccordionEntries WHERE bID = :bID ORDER BY sortOrder LIMIT 0,1": 1
    },
    "richTextsWithFiles": {
        "SELECT description FROM btAccordionEntries WHERE bID = :bID ORDER BY sortOrder LIMIT 1,1": 1        
    },
    "richTextsWithImages": {
        "SELECT description FROM btAccordionEntries WHERE bID = :bID ORDER BY sortOrder LIMIT 1,1": 1        
    }
}
